create extension if not exists pgcrypto;

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  installation_id uuid not null unique,
  management_secret_hash text not null,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  expiration_time bigint,
  thresholds text[] not null default '{}',
  enabled boolean not null default true,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  constraint valid_thresholds check (
    thresholds <@ array['warming','hot','surging','blazing','on fire','inferno']::text[]
  )
);

create table if not exists public.deal_stamp_state (
  thread_id text primary key,
  velocity_label text not null,
  observed_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  subscription_id uuid not null references public.push_subscriptions(id) on delete cascade,
  thread_id text not null,
  velocity_label text not null,
  status text not null default 'pending',
  attempts integer not null default 1,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  delivered_at timestamptz,
  unique (subscription_id, thread_id, velocity_label),
  constraint valid_delivery_status check (
    status in ('pending','delivered','failed_transient','failed_permanent')
  )
);

create index if not exists push_subscriptions_thresholds_idx
  on public.push_subscriptions using gin (thresholds) where enabled;

alter table public.push_subscriptions enable row level security;
alter table public.deal_stamp_state enable row level security;
alter table public.notification_deliveries enable row level security;

revoke all on public.push_subscriptions from anon, authenticated;
revoke all on public.deal_stamp_state from anon, authenticated;
revoke all on public.notification_deliveries from anon, authenticated;

create or replace function public.claim_notification_delivery(
  target_subscription_id uuid,
  target_thread_id text,
  target_velocity_label text
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  claimed boolean := false;
begin
  insert into notification_deliveries (subscription_id, thread_id, velocity_label)
  values (target_subscription_id, target_thread_id, target_velocity_label)
  on conflict (subscription_id, thread_id, velocity_label) do update
    set status = 'pending', attempts = notification_deliveries.attempts + 1,
        error_message = null, updated_at = now()
    where notification_deliveries.status = 'failed_transient'
  returning true into claimed;
  return coalesce(claimed, false);
end;
$$;

revoke all on function public.claim_notification_delivery(uuid, text, text) from public, anon, authenticated;
grant execute on function public.claim_notification_delivery(uuid, text, text) to service_role;

